-- MySQL Script generated by MySQL Workbench
-- Wed Oct 13 22:40:11 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema filmes
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema filmes
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `filmes` DEFAULT CHARACTER SET utf8 ;
USE `filmes` ;

-- -----------------------------------------------------
-- Table `filmes`.`Filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmes`.`Filme` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NULL,
  `ano` YEAR(4) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmes`.`Diretor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmes`.`Diretor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmes`.`Dirige`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmes`.`Dirige` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idDiretor` INT NULL,
  `idFilme` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Dirige_filme_idx` (`idFilme` ASC),
  INDEX `fk_Dirige_Diretor_idx` (`idDiretor` ASC),
  CONSTRAINT `fk_Dirige_filme`
    FOREIGN KEY (`idFilme`)
    REFERENCES `filmes`.`Filme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Dirige_Diretor`
    FOREIGN KEY (`idDiretor`)
    REFERENCES `filmes`.`Diretor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmes`.`Ator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmes`.`Ator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `filmes`.`Participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `filmes`.`Participa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idAtor` INT NULL,
  `idFilme` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Participa_Ator_idx` (`idAtor` ASC),
  INDEX `fk_Participa_Filme_idx` (`idFilme` ASC),
  CONSTRAINT `fk_Participa_Ator`
    FOREIGN KEY (`idAtor`)
    REFERENCES `filmes`.`Ator` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Participa_Filme`
    FOREIGN KEY (`idFilme`)
    REFERENCES `filmes`.`Filme` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
